# Generated by Django 4.1.7 on 2023-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="num_guests",
            field=models.IntegerField(),
        ),
    ]
